//
// Created by dvir on 12/13/18.
//

#ifndef SECONDYEARPROJECT_BIU_DATAREADERSERVER_H
#define SECONDYEARPROJECT_BIU_DATAREADERSERVER_H


class DataReaderServer {

};


#endif //SECONDYEARPROJECT_BIU_DATAREADERSERVER_H
